### ISSUE TITLE
[Suggestion] Add Application Menu Bar

### ISSUE THREAD

**Issue by Peekofwar** [MCJack123/craftos2#108]
Last I checked, the command to add peripherals to the emulator when in vanilla mode produced an error and didn't work... It would be more convenient if peripheral management was handled via an application menu bar at the top of the screen.

**Additional context**
![COS-PC attach vanilla mode](https://user-images.githubusercontent.com/10189526/80985324-0f3b2c80-8dfd-11ea-8bf0-637998073751.JPG)

![COS-PC Menu mockup](https://user-images.githubusercontent.com/10189526/80984465-e23a4a00-8dfb-11ea-917a-95e71f560c93.JPG)

**Comment by daelvn** [comment]
Disagree. I really wouldn't like to see an application menu bar, it would be pretty unfashionable with the rest of the emulator.

On another note, this sounds like a bug or an error in the installation process, not a thing that happens to everyone (because the `attach` command is otherwise fine). Perhaps it'd be much easier to fix this bug than to make it "easier" by adding a whole menu bar.

**Comment by Peekofwar** [comment]
Perhaps it could be an optional thing.

**Comment by MCJack123** [comment]
SDL doesn't have any good way to add a menu bar. If I were to add one, I would either have to write custom UI code to draw the bar manually, or switch to using Qt or some other GUI library. Vanilla mode is really just meant to remove CraftOS-PC-specific APIs so programs can be checked for compatibility with standard CC. Since all vanilla mode does is delete CraftOS-PC APIs, you'd probably be better off deleting everything except `periphemu` from Lua in normal mode.

In the meantime, I'll add an error message to "attach" to check for `periphemu` support.
