### ISSUE TITLE
Erroring on "An unexpected error occured in a lua function: ..."

### ISSUE THREAD

**Issue by devomaa** [MCJack123/craftos2#114]
#**Describe the bug**

**To Reproduce**

1. .Get TRoR API
2. Go to `lua`
3. Type ```
 parallel.waitForAny(function() tror.receive end, function() tror.receiveEvents() end, function() tror.receiveScreen() end)```

**Expected behavior**
Receive Events, and Screen.
**Screenshots**
If applicable, add screenshots or recordings to help explain your problem. You can capture these using F2, F3, or F12. If CraftOS-PC has crashed, paste the stack trace here.
https://i.imgur.com/O95hgIV.png
**Environment (please complete the following information):**
 - OS: [e.g. Windows] Arch Linux
 - Version [e.g. v2.2] 2.3.2
 - Compiled from source? [Yes] [No] No (AUR)

**Additional context**

**Comment by MCJack123** [comment]
This is a bug with the library itself, and not CraftOS-PC. It uses a top-level coroutine override, meaning that any errors that happen in the library (specifically, `receiveEvents`) will end up crashing the entire computer. I'm not sure exactly what the error is because none is being reported. You can attach a debugger and use `catch error` to make it break when the error occurs, then run the code and investigate further. Also, this code was built for an older version of ComputerCraft that may not be entirely compatible with CC: Tweaked 1.8x, so the bug may be caused by some change in CraftOS.
