### ISSUE TITLE
Error Deleting Files, and Declaring Variables

### ISSUE THREAD

**Issue by SyndiShanX** [MCJack123/craftos2#118]
When running my code that works fine on ComputerCraft OS 1.75, I encounter 1 minor issue, and 1 major issue
Examples: 
First Run: (Minor Issue)
![First Run](https://user-images.githubusercontent.com/23367120/85567347-c767a300-b5fe-11ea-8a18-a5fcef22b149.png)
Consecutive Runs: (Major Issue)
![Consecutive Runs](https://user-images.githubusercontent.com/23367120/85568050-5c6a9c00-b5ff-11ea-82cf-815a284e7263.png)

[Server.txt](https://github.com/MCJack123/craftos2/files/4825816/Server.txt)

**Comment by MCJack123** [comment]
1. The first issue is due to your script trying to write an undefined variable (`status1`) to a file. CraftOS-PC shouldn't be erroring when writing nothing, but your script also needs to be fixed to work properly. I'll be fixing support for non-string arguments when writing files.
2. The second issue is [known & fixed](https://github.com/MCJack123/craftos2/commit/a375f31173eb4622296c2d98bd199ad26b2a7d7f), and will be available in the next release. I'm waiting for a few more changes until releasing it.
3. Side note: PLEASE use arrays and `for` loops to store data, instead of having separately-named variables. It will save you pain in the long run since you won't have to replace `status`*x* with `state`*x* 32 times; instead, you only have to do it once. You can replace the initialization code at the beginning of your script with this:
```lua
local state = {}
local synStateColor = {}
local synColor = {}
for i = 1, 32 do
  state[i] = "OFF"
  synStateColor[i] = "colors.red"
  synColor[i] = 0
end
```
instead of the 50 lines in your code.

**Comment by SyndiShanX** [comment]
Ok, thanks a lot! :)
