### ISSUE TITLE
[question] Monitor events

### ISSUE THREAD

**Issue by JustGekto** [MCJack123/craftos2#119]
I have added monitor using "periphemu.create("right","monitor")"
but when i click i obly get mouse_click event.
How do i configure monitor so it gives monitor_touch event.

**Comment by MCJack123** [comment]
Commit 7f26c58 adds support for the `monitor_touch` event by default, but this will not be out for a while. For now, you can either a) listen to the `mouse_click` event in your program, or b) run a background program (through multishell or `parallel`) to listen for `mouse_click` events and queue equivalent `monitor_touch` events. Unfortunately, due to some design shortcomings these do not tell you which monitor they were queued for, but the next version will fix that as well.
