### ISSUE TITLE
mouse_over events

### ISSUE THREAD

**Issue by LoganDark** [MCJack123/craftos2#167]
**Is your feature request related to a problem? Please describe.**
Hover driven interfaces

**Describe the solution you'd like**
`mouse_over` events which fire based on the position of your mouse on-screen

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by SquidDev** [comment]
Isn't there an existing `mouse_move` event, just gated behind a config option?

**Comment by LoganDark** [comment]
> Isn't there an existing `mouse_move` event, just gated behind a config option?

You are correct, but it defaults to being turned off. Is there a particular reason for that?

**Comment by MCJack123** [comment]
Indeed. It's turned off by default because a) moving the mouse would flood the event queue by default, and b) it was intended to offer a preview of a feature that was a work-in-progress in CC:T (SquidDev-CC/CC-Tweaked#434), but it was eventually dropped. If you want the feature, you can set `mouse_move_throttle` to `0`, or a positive number to add throttling in milliseconds (to avoid flooding the queue).

**Comment by LoganDark** [comment]
> moving the mouse would flood the event queue by default

What do you mean flood the event queue? Why don't mouse_drag events have the same problem then?
