### ISSUE TITLE
Make the application support topmost

### ISSUE THREAD

**Issue by Failip420** [MCJack123/craftos2#175]
i really hate alt tabbing my vscode to see the emulator program.

it would be nice if someone implemented top most functionality, so when you right click the title bar of the computer
i want an option that says "top most" or something like that, when it is toggled, no matter what even if i have a code editor in full
screen the computer craft emulator window will always be on top of whatever program is fullscreened :)

**Comment by MCJack123** [comment]
There's already a few options to do this:
* There's some 3rd-party programs to set windows always on top: https://www.howtogeek.com/196958/the-3-best-ways-to-make-a-window-always-on-top-on-windows/
* If your main concern is switching away from VS Code, there's a [CraftOS-PC extension for VS Code](https://marketplace.visualstudio.com/items?itemName=jackmacwindows.craftos-pc) that adds support for opening CraftOS terminals inside the IDE.

I'll also consider adding an option in the context menu to avoid having to use 3rd-party stuff. Since I use SDL, all of the Windows stuff is abstracted away, making accessing low-level stuff like that more difficult, but I'll see what I can do.

**Comment by LoganDark** [comment]
Just spam [`SDL_RaiseWindow`](https://wiki.libsdl.org/SDL_RaiseWindow).

Pros:
- Flickery and glitchy
- Uses CPU constantly
- Steals focus away from other applications
- A great experience for the user

Cons:
- None! Feel free to make a pull request if you think something can be made worse.

**Comment by MCJack123** [comment]
Due to the significant complexity (if not impossibility) of adding stuff to the context menu, I've decided to add a keystroke to activate it. Now pressing Ctrl+F8 (Cmd+F8) will toggle always-on-top mode. This functionality is supported on Windows, Mac (excluding console builds), and Linux when using X11 (Wayland not supported).
