### ISSUE TITLE
Align fullscreen window better to fit extra pixel

### ISSUE THREAD

**Issue by hugeblank** [MCJack123/craftos2#180]
**Is your feature request related to a problem? Please describe.**
The problem is this frame around the screen that is clearly seen when inverting the colors, and then clearing the screen. It looks like an entire extra pixel in width and height could be granted if the black part of the terminal was shifted properly aligned with the top left corner:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16393543/103436299-dee7a000-4bce-11eb-9ec8-5b22fe89bc6a.png">

This also affects mouse cursor things, rather than being able to slam my cursor on the left edge of the screen to access a menu (which you can't do in native CC anyways, but should be possible here), I have to slightly nudge my cursor to the right. This task is made more difficult with a track pad.

**Describe the solution you'd like**
I'd like to have a full screen of pixels, and the ability to be lazy when I want something on an edge.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hugeblank** [comment]
I'm not going to close this but I will say I "solved" it. There's two different "fullscreen" modes. We'll call them 'your' way, and the 'regular' way. The regular way is to press the green "expand to fullscreen" icon provided by MacOS. That method leaves behind the bars and offsets, and also persists through quitting the app. Your way is by setting that config option "start in fullscreen" to true and persists in the same way. However, your way also fixes the complaint I had here. If you could find a way to merge the behaviors into one that would be cool.

**Comment by hugeblank** [comment]
Follow up 2: It seems that after closing out the app and then reopening it, the regular method of going fullscreen seems to adopt the same issue your method does, and I can't seem to do anything about it, even toggling the `startFullscreen` value changes nothing.

**Comment by MCJack123** [comment]
This is intentional behavior due to how the margins work in normal mode. The reason this occurs is that the window isn't perfectly sized to fit all of the characters equally, so there's extra margin space on the side. Trying to center the screen would cause more problems than it's worth.

If you want to have the margins filled with the computer background color, you can enable standards mode (though this will affect some other things as well). I've also made it so that the margins stretch properly to the edges if the window is resized.

Regarding mouse coordinates: this is a bug, and it should have been giving coordinates for the edges when clicking in the margin. I've fixed this as well.
