### ISSUE TITLE
Running 

### ISSUE THREAD

**Issue by herrigesmt** [MCJack123/craftos2#186]
**Describe the bug**
Am unable to start CraftOS from Ubuntu running WSL2.

**To Reproduce**
1. Followed the steps for installing on Ubuntu described in the README
2. Ran `craftos` in my ubuntu terminal
3. Encounter error code, fail to launch

**Expected behavior**
CraftOS to launch

**Screenshots**
This is the error codes I am receiving in my terminal:

```console
~$ craftos
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
error: XDG_RUNTIME_DIR not set in the environment.
```

**Environment (please complete the following information):**
 - OS: Windows 10/Ubuntu
 - OS Version: 2004/10.0.19041 | Ubuntu 20.04
 - CraftOS-PC Version: 2.5.1.1
 - Compiled from source? No

**Additional context**
This may very well be something I've done wrong on my end or an error in my WSL setup. I am relatively new to using Linux and especially WSL (< 1 year). If you have any insights or have experienced an issue like this before I would appreciate it greatly.

**Comment by LoganDark** [comment]
1. WSL does not offer GUI functionality; you would have to use the experimental CLI mode, or install an X server (VcXsrv?)
2. `error: XDG_RUNTIME_DIR not set in the environment.` - you will have to set the environment variable `XDG_RUNTIME_DIR`, see [here](https://stackoverflow.com/a/59843603) for a possible solution

**Comment by LoganDark** [comment]
I would recommend just running the Windows version of CraftOS-PC. Windows builds are prioritized by Jack.

**Comment by MCJack123** [comment]
Indeed, running under WSL requires an X server to be running under Windows due to Linux using X instead of Windows's DWM. This is especially true under WSL2, which doesn't even have access to the Windows API at all (since it's in a VM). Your options are:
1. Install an X server such as VcXsrv, and run `export DISPLAY=:0` before running CraftOS-PC.
2. Run CraftOS-PC in CLI mode. (@LoganDark: not experimental! It's fully supported.)
3. Use the CraftOS-PC extension and Remote-WSL capabilities in VS Code to run it inside VS Code under WSL instead.
4. Run CraftOS-PC under Windows instead of WSL.
