### ISSUE TITLE
add fedora repo

### ISSUE THREAD

**Issue by devomaa** [MCJack123/craftos2#207]
**Is your feature request related to a problem? Please describe.**
fedora doesn't have a repo for craftos-pc

**Describe the solution you'd like**
add a repo in https://copr.fedorainfracloud.org/coprs/ or a similar fedora repo thingy

**Describe alternatives you've considered**
nothing except some hacky solutions

**Additional context**
i use fedora now yey 🎉

**Comment by MCJack123** [comment]
I'm not familiar enough with Fedora, and I'd rather have someone who knows more about its packaging system maintain the package. If you want to maintain it yourself, you can take a look at [how I set up the Debian control files](https://launchpad.net/~jackmacwindows/+archive/ubuntu/ppa/+sourcefiles/craftos-pc/1:2.5.5-bionic1/craftos-pc_2.5.5-bionic1.debian.tar.xz) for a start on how to make that work. If you do make a Fedora package, I'll link it on the website/readme. Otherwise, you'll have to build from source (which shouldn't really be too hard anyway - it's just `./configure && make && sudo make install`).

**Comment by LeMoonStar** [comment]
There now is a pre-built package repository for fedora, you can use it by enabling the repository like this:
```sh
sudo dnf copr enable lemoonstar/CraftOS-PC
```
and then install CraftOS-PC using
```sh
sudo dnf install craftos-pc
```

Installing the C++ API is done by executing
```sh
sudo dnf install craftos-pc-devel
```

The spec files are available in [this github repo](https://github.com/LeMoonStar/craftos2-rpm)
