### ISSUE TITLE
Window State Memory (Size, Screen Position)

### ISSUE THREAD

**Issue by CodingButter** [MCJack123/craftos2#234]
**Is your feature request related to a problem? Please describe.**
I develop with a specific window configuration e.g vs code on left monitor and cc sharing the right monitor with other windows. My other windows remember where they were when i last closed them (sometimes i have to hit ctrl and the close button) but when i start up CraftOS-PC it starts center center at a set size.

**Describe the solution you'd like**
It would be nice to have both the emulator and any peripherals remember their last position and size after closing (either by default or with ctrl close) this way when I inevitably accidently close the window it will open back up to where i left it

**Describe alternatives you've considered**
I could just deal with the current behavior since its a minor feature that may only benefit me 
**Additional context**
I am a Twitch streamer so its beneficial for this functionality for all my windows. as my entire set up needs to be a specific way when preparing to stream

**Comment by MCJack123** [comment]
You can use the `computerWidth` and `computerHeight` config settings to set the size of the computer (in characters) on boot. There's also `default` versions of each, which are global to all computers.

As for positioning, unfortunately this is not possible at the moment. I already tell SDL to use an undefined position, but SDL interprets this as wanting to be centered, instead of passing `CW_USEDEFAULT` when creating the window. You could open an issue on the [SDL repo](/libsdl-org/SDL), and if it's implemented CraftOS-PC will be able to use it immediately.
