### ISSUE TITLE
textutils.unserialiseJSON behaves strangely

### ISSUE THREAD

**Issue by ChickChicky** [MCJack123/craftos2#246]
**Describe the bug**
I tried parsing some JSON using `textutils.unserialiseJSON`, but for some reason the data that got read previously is also included in the output
*tetris.lua (just the breaking point)*
```lua
local handle, err = fs.open('.tetris','r');
local data = textutils.unserialiseJSON(handle.readAll());
print(#data.scores);
handle.close();
-- then it loads the scores from a server and inserts them at the end of data.scores, for testing, I only have 1 score on the server
```
*.tetris*
```json
{"scores":[]}
```
The first time I run the code, no problem, 0 gets printed out, but the next time I try, I get 1 and then 2, so forth so on
I tried keeping only the piece of code that doesn't work and put it in *len.lua*, and when I run it after I ran *tetris.lua* 2 times, Iget this:
![image](https://user-images.githubusercontent.com/91527355/166815000-8dfe5324-0ac5-4da3-a3fc-650ed1807205.png)

**How To Reproduce**
just put the following code in a file:
```lua
local handle, err = fs.open('data.json','r');
local data = textutils.unserialiseJSON(handle.readAll());
print(#data.scores);
table.insert(data.scores,'test');
handle.close();
```
and this in *data.json*
```json
{"scores":[]}
```
running it over and over seems to always increase the value even if nothing is being written
![image](https://user-images.githubusercontent.com/91527355/166816069-7a021fdd-dc1c-4bbb-92d9-53b8f3e303ae.png)

also, rebooting the computer temporarely resolves the issue
EDIT: the problem seems to have fixed itself

**Environment (please complete the following information):**
 - Windows 10
 - CraftOS-PC Version 2.6.5.1
 - Downloaded from website / Not built manually

This is my first bug report, so please let me know if I should anything to make things more clear or anything else

**Comment by MCJack123** [comment]
This is because CraftOS returns a special value `textutils.empty_json_array` when it encounters an empty array. This variable should normally be impossible to modify, but `table.insert` does not respect the metatable, so it can pass right through and affect that global variable. This is the same behavior as CC:T, so I'm not going to fix it. [I've made an issue about it on the CC:T repo, but don't expect it to be fixed.](https://github.com/cc-tweaked/CC-Tweaked/issues/1088)

(I have a PR open to [note the special values in the docs](https://github.com/cc-tweaked/CC-Tweaked/pull/1058), which I was surprised didn't exist before, but it hasn't been merged yet.)
