### ISSUE TITLE
CraftOS-PC does not support mounting samba or unc shares on Windows

### ISSUE THREAD

**Issue by EmmaKnijn** [MCJack123/craftos2#282]
**Describe the bug**
I'm unable to mount both a samba share and its UNC driveletter counterpart

**To Reproduce**
1. Try mounting a mounted samba with for example `--mount-ro /mnt/screenshots=Z:\Programs\sharex` or `--mount-ro /mnt/screenshots=\\10.10.30.35\Ruben-NAS\Programs\sharex`
2. See it not being mounted and visible with `ls`, while visible with mounts.list()

**Expected behavior**
I expect the mounted file share to be available from within CC

**Screenshots**
![Code_ubGThqa3ik](https://user-images.githubusercontent.com/64010592/194757589-2f18604b-a600-459a-8f27-f7ae5169ac00.png)
![Code_IlJE3ZsXPV](https://user-images.githubusercontent.com/64010592/194757601-f3b68122-0edd-41b7-9919-cd643d6804c2.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - OS Version: 21H2
 - CraftOS-PC Version: v2.7.1
 - Compiled from source? No

**Additional context**
Mounting from a relative directory with `--mount-ro /code=./src` works fine

**Comment by EmmaKnijn** [comment]
May be a feature report rather than a bug report, depending on how its interpreted

**Comment by MCJack123** [comment]
I have tested this myself and can not reproduce the issue. I'm able to connect to both SMB shares on the network, as well as WSL virtual shares, using both the `mount` command and `--mount` argument. One caveat is that you need to make sure the share has been mounted with username/password first - otherwise, it will not be able to connect.
