### ISSUE TITLE
Add clickable URLs when printed

### ISSUE THREAD

**Issue by tomodachi94** [MCJack123/craftos2#289]
**Is your feature request related to a problem? Please describe.**
I'm pretty frustrated when a URL is printed to the terminal and I can't click on it.

**Describe the solution you'd like**
I would like to be able to `Ctrl+Left-click` on a URL and have it open in my default web browser in a similar manner to Visual Studio Code.

**Describe alternatives you've considered**

**Additional context**
![VSCode's indicator of a clickable link](https://user-images.githubusercontent.com/68489118/198912221-a8c970d6-e4e9-4326-9197-1c4b313ac333.png)

**Comment by tomodachi94** [comment]
I totally understand if this is out of the scope of this emulator, just figured it would be a nice QoL thing,

**Comment by MCJack123** [comment]
Unfortunately, this would be quite difficult to implement on the C side. This is because a) the screen is just a matrix of characters with no easy way to detect continuous strings like URLs, and b) different OSes have different ways of implementing opening URLs, which makes the code really messy. It also starts to get in the way of programs that may not want that functionality present.

If you'd like to modify your shell to add this feature, it shouldn't be way too difficult to do. You could modify `print` to detect full URLs and then map them to places on the screen, then have multishell detect those clicks and automatically open them using a custom plugin. You'd need to write a bit of C++ code to implement the URL opener, but the plugin API should make this pretty smooth to do.
