### ISSUE TITLE
cli mode doesn't handle keys correctly

### ISSUE THREAD

**Issue by 1e1001** [MCJack123/craftos2#304]
**Describe the bug**
cli mode differs quite noticably compared to graphical mode in terms of key codes, including:
- using shift or ctrl gives many characters different codes
- the following keys have different codes: home, end, pgup, pgdown, `, del
- shift/ctrl/alt/caps do not send codes (limitation of terminals, maybe send press+key+release or some combination to send a single press)
- ctrl+v does not paste (would be nice for consistency)
- ctrl+t and ctrl+r do not work

**To Reproduce**
1. Open craftos in cli and graphical modes
2. on both, run lua and the expression `while 1 do local a,b=os.pullEvent()if a=="key"or a=="key_up"then print(a,b)end end`
3. go wild on the keyboard :)

**Expected behavior**
They should behave exactly the same

**Screenshots**
pressing the same keys on both:
![image](https://user-images.githubusercontent.com/22437115/209710420-42d2ff64-8fa2-4b32-a7dc-fb581ecf78c6.png)![image](https://user-images.githubusercontent.com/22437115/209710436-4c2367ca-9122-4fb7-947e-f54f1b810ee4.png)

**Environment (please complete the following information):**
 - OS: Arch Linux
 - OS Version: rolling
 - CraftOS-PC Version: v2.7.2
 - Compiled from source? No

**Additional context**
i wanna use cli mode :)

**Comment by MCJack123** [comment]
Command line terminals don't give as much flexibility with handing input, so I have to make do with what's possible.

- There's no event for releasing keys in ncurses, so `key_up` events have to be emitted immediately.
- Modifier keys don't give events either, so I've had to add some workarounds for programs that require those keys (like edit) - by default, the Home/End keys simulate Ctrl/Alt, and holding Shift on each will press the original key. This behavior can be configured with the `cliControlKeyMode` config option (in `global.json` only). For more info, [see the config docs](https://www.craftos-pc.cc/docs/config).
- Consoles handle Ctrl key combos on their own, blocking the program from accepting them normally, so it's impossible to accept arbitrary combos like Ctrl+V/T/S/R. You may be able to paste with the terminal-provided shortcut (right-click on Windows, or Shift+Ctrl+V on many other terminals), but this would use typing instead of a single `paste` event, as terminals don't provide an event for pasting.
