### ISSUE TITLE
Release iOS in more countries

### ISSUE THREAD

**Issue by mahtan** [MCJack123/craftos2#335]
Hi, at first thank you for creating this program, would it be possible to make it available on the app store for more countries ? I'm in France and the app is unavailable in my country, i used it with testflight but the app as expired and the number of install is now full.

Thank you

**Comment by MCJack123** [comment]
Unfortunately, this is a limitation of the French government - they require a long-winded documentation process for any app that uses encryption (which includes HTTPS in OpenSSL), and I don't speak French, so it's more trouble than it's worth to get it on the French App Store. Petition your government to stop this privacy-harming practice. (Note: France is the only country where CCPC is unavailable on iOS.)

As for TestFlight, that's because it's been over 3 months since the last build, so it expired. A new set of builds will be available soon with v2.8 development, so please wait for those to be ready.
