### ISSUE TITLE
On Windows %R is not a valid format specifier for os.date

### ISSUE THREAD

**Issue by MasonGulu** [MCJack123/craftos2#352]
**Describe the bug**
This is a platform specific issue. On Linux calling `os.date("%R")` results in the correct formatting. On Windows calling the same snippet results in an error.

**To Reproduce**
1. Open `lua` prompt
2. Type in `os.date("%R")`
3. Compare behavior on Linux vs. Windows.

**Expected behavior**
No Crash.

**Screenshots**
![image](https://github.com/MCJack123/craftos2/assets/70228812/1351c173-3b00-4f9d-80fc-00393ef55c31)

**Environment (please complete the following information):**
 - OS: Windows 10 / Kubuntu 22.04
 - CraftOS-PC Version: 2.8.1
 - Compiled from source? No

**Additional context**

**Comment by MasonGulu** [comment]
minerobber pointed out this relevant code
https://github.com/MCJack123/craftos2-lua/blob/lua-5.2/src/loslib.c#L28-L35

**Comment by MineRobber9000** [comment]
Specifically, if `LUA_USE_POSIX` is not defined, Lua restricts itself to a set of format specifiers that it *knows* will be available (`%R` is a C99 addition according to Jack so on a C89 system it wouldn't be available). Since Windows is not POSIX, `%R` isn't in the list of allowed format specifiers, and Lua responds with an error.
