### ISSUE TITLE
Improperly sanitizied paths cause filesystem escape (Windows)

### ISSUE THREAD

**Issue by graypinkfurball** [MCJack123/craftos2#366]
**Describe the bug**
You can escape the computer folder and access files anywhere without permission or notice,
by obfuscating `..`s to bypass the internal check preventing parent directory traversal.

**To Reproduce**
Link: [Microsoft - Naming Conventions](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions)
You can mix the following reserved characters `< > : " | ?` (excludes `/ \ *`) into a `..` to bypass the check, e.g. `<..>` or `..|`.
Afterwards the reserved characters appear to be silently dropped by the filesystem.

1. Use the emulator on a windows
2. Type `cd ..|` followed by `ls` multiple times.
3. Observe escaping the computer folder.

**Expected behavior**
For the reserved characters to be filtered out by the `fs` api before the internal check against `..`s, preventing parent directory traversal.

**Screenshots**

![image](https://github.com/user-attachments/assets/11ffe307-381e-4457-b0f3-fd8c298882a7)

**Environment**
 - OS: **Windows 11 Home**
 - OS Version: **23H2**
 - CraftOS-PC Version: **v2.8.2**
 - Compiled from source? **No**

**Comment by graypinkfurball** [comment]
Also null bytes appear not to be sanitized either.
The `fs` api mostly behaves as though the input string ends at the first null byte, probably from underlying API expecting a null-terminated string.
`fs.list()` acts odd with the presence of a null byte, it still throws `No such file` and `Not a directory` if the path portion before the null byte doesn't exist or is a file, but otherwise just returns `{}` and it doesn't throw any error for `..` like it should.
also `fs.attribute("..\0")` appears to be able to read the timestamps of the `computer` folder.

**Comment by Ale32bit** [comment]
This kind of issue should NOT be disclosed publicly: https://github.com/MCJack123/craftos2/security

**Comment by MCJack123** [comment]
Transferring to a security advisory.

**Comment by MCJack123** [comment]
@graypinkfurball Since I apparently can't reply in the advisory, I'll do it here:

Well, the vulnerability is public now, and there's a patch available, so it's not much use to delete the issue. I was a bit annoyed that you didn't take any precautions, but it's also partially my fault for not having a security policy defined. What's done is done though, and I at least appreciate that you notified me in some way about this - it's better to have to rush a security fix out early in the morning, than to have a 0-day lingering forever.
