### ISSUE TITLE
MAC: Only working on 10.15 or later

### ISSUE THREAD

**Issue by Le0Developer** [MCJack123/craftos2#56]
Running the app on macOS 10.13.6 throws this error.
---
https://imgur.com/a/0XtewVS

**Comment by MCJack123** [comment]
I found that the Mac build shipped an old version of a library that is not compatible with the current build. I'm not sure if this bug is related to that, but I'm going to assume it is. I updated the latest build on the releases page to fix the old library; download that and see if it works.

**Comment by Le0Developer** [comment]
Still not working.
Finder even shows a "not compatible" sign on the icon.

https://imgur.com/a/giNQGL2

**Comment by MCJack123** [comment]
I've been able to reproduce this bug on a machine running Mojave. I have no idea why this bug is happening, since the app is set to require 10.9.5 or later in Info.plist. For now, you can run it by right-clicking the app -> Show Package Contents, then going into Contents => MacOS and opening `craftos` directly. I'm going to keep looking to see what could be causing this bug.

**Comment by MCJack123** [comment]
Adding the `-mmacosx-version-min` flag to the Makefile seems to have fixed this issue.
