### ISSUE TITLE
Complete fail on Raspberry Pi 

### ISSUE THREAD

**Issue by Ocawesome101** [MCJack123/craftos2#61]
I recently took a trip, and, my laptop being broken, I took along my Raspberry Pi. While craftos-pc compiles with no issues, running it seems to error out every single file it runs— including `bios.lua`. As a result, I ended up having to use CCEmuX. 

I can only assume that this is either a bug with your code, or with the underlying armhf Lua interpreter.

**Comment by MCJack123** [comment]
This is caused by some faulty line endings that the Raspi version of git doesn't fix. I've fixed the line endings in the latest commits to both branches of the [ROM repository](https://github.com/MCJack123/craftos2-rom). (Make sure you cloned the right branches: `craftos2/v2.2` corresponds to `craftos2-rom/master`, and `craftos2/master` corresponds to `craftos2-rom/v2.1`. Using `craftos2-rom/master` with `craftos2/master` works OK, but using `craftos2-rom/v2.1` with `craftos2/v2.2` does not work.)

**Comment by MCJack123** [comment]
Also, you can run `sudo find /usr/local/share/craftos -type f -exec dos2unix {} \;` to fix the line endings without pulling again. (You might need to install `dos2unix` if you don't have it.)

**Comment by Ocawesome101** [comment]
Thank you! I will do this.
