### ISSUE TITLE
MIDI + SF2 reading/playback support

### ISSUE THREAD

**Issue by LDDestroier** [MCJack123/craftos2#97]
I have a big ol' 72 key MIDI piano, and I want to be able to make a simple MIDI sequencer in CraftOS. To be honest I have no further justification for such a feature

**Comment by MCJack123** [comment]
I've added MIDI support through `speaker.playLocalMusic` (as well as playing any other local sound file), and `speaker.playSound` will also play MIDI sound files. Soundfont support is also available through `speaker.setSoundFont`, which expects a real path to the soundfont (outside the computer).

Unfortunately, MIDI input is not possible since SDL does not have any sort of MIDI input support. You could possibly use a mapping tool to map each piano key to a keyboard key, though.

**Comment by LDDestroier** [comment]
I've already mapped my piano to keyboard keys for each note block sound, but that was such a tedious process. I'm sure I could probably work something out, though.
